/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pe.edu.pucp.centralizacionbancariasoft.forms;

import java.awt.Color;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import pe.edu.pucp.centralizacionbancariasoft.ManagerFormatoMacros;

/**
 *
 * @author jyalico
 */
public class FrmMacroBancos extends javax.swing.JPanel {

    /**
     * Creates new form frmMacroBancos
     */
    private double montoMinimo;
    private String fechaBloqueo;
    private boolean editandoMonto;
    private boolean editandoFecha;
    private ManagerFormatoMacros manager;
    private boolean rutaSicopSeteada;
    private boolean rutaCenturiaSeteada;

    private boolean validarFormatoFecha(String fecha) {
        try {
            // Intentar crear un objeto Date a partir de la fecha
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false); // Desactivar la flexibilidad para permitir solo fechas válidas
            sdf.parse(fecha);
            return true; // Si la fecha se puede parsear correctamente, el formato es válido
        } catch (ParseException e) {
            // Si ocurre una excepción, la fecha no tiene el formato correcto
            return false;
        }
    }
    
    private void cambiarColorDelBoton() {
        if (rutaSicopSeteada || rutaCenturiaSeteada) {
            BotenGenerarMacro.setBackground(Color.decode("#042354")); // Cambiar color del botón
            BotenGenerarMacro.setForeground(Color.WHITE); // Cambiar color del texto a blanco
            BotenGenerarMacro.setEnabled(true); // Habilitar el botón
        } else {
            BotenGenerarMacro.setBackground(UIManager.getColor("Button.background")); // Restaurar color por defecto del botón
            BotenGenerarMacro.setForeground(UIManager.getColor("Button.foreground")); // Restaurar color del texto por defecto
            BotenGenerarMacro.setEnabled(false); // Deshabilitar el botón
        }
    }
    
    public double getMontoMinimo() {
        return montoMinimo;
    }

    public void setMontoMinimo(String montMin) {
        // Validar si es un número
        try {
            double numero = Double.parseDouble(montMin);
            // Formatear el número con dos decimales
            DecimalFormat df = new DecimalFormat("#.##");
            df.setMinimumFractionDigits(2); // Para completar con ceros si tiene menos de 2 decimales
            df.setMaximumFractionDigits(2); // Para truncar si tiene más de 2 decimales
            this.montoMinimo = Double.parseDouble(df.format(numero));
        } catch (NumberFormatException e) {
            System.out.println("El valor ingresado no es un número válido.");
            this.montoMinimo = 1.00; // O puedes lanzar una excepción, según lo que prefieras
        }
        TextfieldMontoMin.setText(String.format("%.2f", this.montoMinimo));
    }
    

    public String getFechaBloqueo() {
        return fechaBloqueo;
    }

    public void setFechaBloqueo(String fechaBloqu) {
        // Verificar si la fecha recibida tiene el formato "dd/mm/aaaa"
        if (validarFormatoFecha(fechaBloqu)) {
            this.fechaBloqueo = fechaBloqu;
        } else{
            this.fechaBloqueo = "31/12/2030";
        }
        TextfieldFechaBloqueo.setText(this.fechaBloqueo);
    }
    
    
    
    public FrmMacroBancos() {
        initComponents();
        montoMinimo = 1.0;
        fechaBloqueo = "31/12/2030";
        editandoMonto = false;
        editandoFecha = false;
        rutaSicopSeteada = false;
        rutaCenturiaSeteada = false;
        TextfieldFechaBloqueo.setText(fechaBloqueo);
        TextfieldMontoMin.setText(String.format("%.2f", this.montoMinimo));
        manager = new ManagerFormatoMacros();
        cambiarColorDelBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonMetro2 = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        PanelTitulo = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelInstr = new javax.swing.JPanel();
        LabelInstr = new javax.swing.JLabel();
        PanelCarga = new javax.swing.JPanel();
        PanelSicop = new javax.swing.JPanel();
        BotonBorrarSicop = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        BotonSicop1 = new javax.swing.JButton();
        LabelSicop = new javax.swing.JLabel();
        TextfieldSicop = new javax.swing.JTextField();
        PanelCenturia = new javax.swing.JPanel();
        BotonBorrarCenturia = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        BotonCenturia = new javax.swing.JButton();
        LabelCenturia = new javax.swing.JLabel();
        TextfieldCenturia = new javax.swing.JTextField();
        PanelConfig = new javax.swing.JPanel();
        BotonEditarMontoMin = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        LabelMontoMin = new javax.swing.JLabel();
        TextfieldFechaBloqueo = new javax.swing.JTextField();
        LabelFechaBloqueo = new javax.swing.JLabel();
        TextfieldMontoMin = new javax.swing.JTextField();
        BotonEditarFechaBloque = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        BotenGenerarMacro = new javax.swing.JButton();

        rSButtonMetro2.setText("rSButtonMetro2");

        setBackground(new java.awt.Color(155, 186, 235));
        setPreferredSize(new java.awt.Dimension(750, 400));

        PanelTitulo.setBackground(new java.awt.Color(155, 186, 235));
        PanelTitulo.setForeground(new java.awt.Color(155, 186, 235));

        LabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        LabelTitulo.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitulo.setText("GENERAR EXCELS PARA LAS MACROS BCP Y BBVA");
        LabelTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelInstr.setBackground(new java.awt.Color(155, 186, 235));

        LabelInstr.setBackground(new java.awt.Color(0, 0, 0));
        LabelInstr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LabelInstr.setForeground(new java.awt.Color(0, 0, 0));
        LabelInstr.setText("Seleccione los archivos SICOP y CENTURIA");
        LabelInstr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));

        javax.swing.GroupLayout PanelInstrLayout = new javax.swing.GroupLayout(PanelInstr);
        PanelInstr.setLayout(PanelInstrLayout);
        PanelInstrLayout.setHorizontalGroup(
            PanelInstrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelInstr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelInstrLayout.setVerticalGroup(
            PanelInstrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInstrLayout.createSequentialGroup()
                .addComponent(LabelInstr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelCarga.setBackground(new java.awt.Color(155, 186, 235));

        PanelSicop.setBackground(new java.awt.Color(155, 186, 235));

        BotonBorrarSicop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pucp/centralizacionbancariasoft/img/delete30x30.png"))); // NOI18N
        BotonBorrarSicop.setColorHover(new java.awt.Color(155, 186, 235));
        BotonBorrarSicop.setColorNormal(new java.awt.Color(155, 186, 235));
        BotonBorrarSicop.setColorPressed(new java.awt.Color(155, 186, 235));
        BotonBorrarSicop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarSicopActionPerformed(evt);
            }
        });

        BotonSicop1.setBackground(new java.awt.Color(4, 35, 84));
        BotonSicop1.setForeground(new java.awt.Color(255, 255, 255));
        BotonSicop1.setText("Cargar SICOP");
        BotonSicop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSicop1ActionPerformed(evt);
            }
        });

        LabelSicop.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelSicop.setForeground(new java.awt.Color(255, 255, 255));
        LabelSicop.setText("Archivo:");

        TextfieldSicop.setText("Seleccione un archivo");
        TextfieldSicop.setEnabled(false);
        TextfieldSicop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldSicopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSicopLayout = new javax.swing.GroupLayout(PanelSicop);
        PanelSicop.setLayout(PanelSicopLayout);
        PanelSicopLayout.setHorizontalGroup(
            PanelSicopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSicopLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BotonSicop1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LabelSicop, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextfieldSicop, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonBorrarSicop, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSicopLayout.setVerticalGroup(
            PanelSicopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSicopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BotonSicop1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(LabelSicop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelSicopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSicopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBorrarSicop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextfieldSicop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCenturia.setBackground(new java.awt.Color(155, 186, 235));

        BotonBorrarCenturia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pucp/centralizacionbancariasoft/img/delete30x30.png"))); // NOI18N
        BotonBorrarCenturia.setColorHover(new java.awt.Color(155, 186, 235));
        BotonBorrarCenturia.setColorNormal(new java.awt.Color(155, 186, 235));
        BotonBorrarCenturia.setColorPressed(new java.awt.Color(155, 186, 235));
        BotonBorrarCenturia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarCenturiaActionPerformed(evt);
            }
        });

        BotonCenturia.setBackground(new java.awt.Color(4, 35, 84));
        BotonCenturia.setForeground(new java.awt.Color(255, 255, 255));
        BotonCenturia.setText("Cargar CENTURIA");
        BotonCenturia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCenturiaActionPerformed(evt);
            }
        });

        LabelCenturia.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        LabelCenturia.setForeground(new java.awt.Color(255, 255, 255));
        LabelCenturia.setText("Archivo:");

        TextfieldCenturia.setText("Seleccione un archivo");
        TextfieldCenturia.setEnabled(false);
        TextfieldCenturia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldCenturiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCenturiaLayout = new javax.swing.GroupLayout(PanelCenturia);
        PanelCenturia.setLayout(PanelCenturiaLayout);
        PanelCenturiaLayout.setHorizontalGroup(
            PanelCenturiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCenturiaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BotonCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LabelCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextfieldCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonBorrarCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCenturiaLayout.setVerticalGroup(
            PanelCenturiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCenturiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BotonCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(LabelCenturia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCenturiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCenturiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonBorrarCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextfieldCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelConfig.setBackground(new java.awt.Color(155, 186, 235));

        BotonEditarMontoMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pucp/centralizacionbancariasoft/img/edit30x30.png"))); // NOI18N
        BotonEditarMontoMin.setColorHover(new java.awt.Color(155, 186, 235));
        BotonEditarMontoMin.setColorNormal(new java.awt.Color(155, 186, 235));
        BotonEditarMontoMin.setColorPressed(new java.awt.Color(155, 186, 235));
        BotonEditarMontoMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarMontoMinActionPerformed(evt);
            }
        });

        LabelMontoMin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelMontoMin.setForeground(new java.awt.Color(255, 255, 255));
        LabelMontoMin.setText("Monto mínimo:");

        TextfieldFechaBloqueo.setText("fechaBloqueo");
        TextfieldFechaBloqueo.setEnabled(false);
        TextfieldFechaBloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldFechaBloqueoActionPerformed(evt);
            }
        });

        LabelFechaBloqueo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LabelFechaBloqueo.setForeground(new java.awt.Color(255, 255, 255));
        LabelFechaBloqueo.setText("Fecha bloqueo:");

        TextfieldMontoMin.setText("Monto mínimo");
        TextfieldMontoMin.setEnabled(false);
        TextfieldMontoMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextfieldMontoMinActionPerformed(evt);
            }
        });

        BotonEditarFechaBloque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pucp/centralizacionbancariasoft/img/edit30x30.png"))); // NOI18N
        BotonEditarFechaBloque.setColorHover(new java.awt.Color(155, 186, 235));
        BotonEditarFechaBloque.setColorNormal(new java.awt.Color(155, 186, 235));
        BotonEditarFechaBloque.setColorPressed(new java.awt.Color(155, 186, 235));
        BotonEditarFechaBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarFechaBloqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConfigLayout = new javax.swing.GroupLayout(PanelConfig);
        PanelConfig.setLayout(PanelConfigLayout);
        PanelConfigLayout.setHorizontalGroup(
            PanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfigLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(LabelMontoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TextfieldMontoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonEditarMontoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LabelFechaBloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TextfieldFechaBloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BotonEditarFechaBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        PanelConfigLayout.setVerticalGroup(
            PanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonEditarMontoMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelConfigLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConfigLayout.createSequentialGroup()
                        .addGroup(PanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelMontoMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextfieldMontoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(PanelConfigLayout.createSequentialGroup()
                        .addGroup(PanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFechaBloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextfieldFechaBloqueo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(BotonEditarFechaBloque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BotenGenerarMacro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BotenGenerarMacro.setActionCommand("Generar ");
        BotenGenerarMacro.setEnabled(false);
        BotenGenerarMacro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BotenGenerarMacro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotenGenerarMacro.setLabel("<html>Generar Archivos</html>");
        BotenGenerarMacro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotenGenerarMacroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCargaLayout = new javax.swing.GroupLayout(PanelCarga);
        PanelCarga.setLayout(PanelCargaLayout);
        PanelCargaLayout.setHorizontalGroup(
            PanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSicop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCenturia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelCargaLayout.createSequentialGroup()
                .addComponent(PanelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelCargaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BotenGenerarMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCargaLayout.setVerticalGroup(
            PanelCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(PanelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSicop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelCenturia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotenGenerarMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelInstr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelInstr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextfieldSicopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldSicopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldSicopActionPerformed

    private void BotonBorrarSicopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarSicopActionPerformed
        // TODO add your handling code here:
        manager.setRutaSicop("");
        TextfieldSicop.setText("Seleccione un archivo");
        rutaSicopSeteada = false;
        cambiarColorDelBoton();
    }//GEN-LAST:event_BotonBorrarSicopActionPerformed

    private void BotonBorrarCenturiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarCenturiaActionPerformed
        // TODO add your handling code here:
        manager.setRutaCenturia("");
        TextfieldCenturia.setText("Seleccione un archivo");
        rutaCenturiaSeteada = false;
        cambiarColorDelBoton();
    }//GEN-LAST:event_BotonBorrarCenturiaActionPerformed

    private void TextfieldCenturiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldCenturiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldCenturiaActionPerformed

    private void BotonEditarMontoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarMontoMinActionPerformed
        // TODO add your handling code here:
        //System.out.println("presionando editar");
        //Si no estoy editando entonces em=false y textfield = false
        //cada vez que hago click cambio el valor
        if(editandoMonto){
            BotonEditarMontoMin.setIcon(new javax.swing.ImageIcon(getClass().getResource
        ("/pe/edu/pucp/centralizacionbancariasoft/img/edit30x30.png")));
            
            //System.out.println("Monto min: "+TextfieldMontoMin.getText());
            setMontoMinimo(TextfieldMontoMin.getText());
        }else{
            BotonEditarMontoMin.setIcon(new javax.swing.ImageIcon(getClass().getResource
        ("/pe/edu/pucp/centralizacionbancariasoft/img/checked30x30.png")));
        }
        editandoMonto = !editandoMonto;
        TextfieldMontoMin.setEnabled(editandoMonto);
        //setMontoMinimo(TextfieldMontoMin.getSelectedText());
        
    }//GEN-LAST:event_BotonEditarMontoMinActionPerformed

    private void TextfieldFechaBloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldFechaBloqueoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextfieldFechaBloqueoActionPerformed

    private void TextfieldMontoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextfieldMontoMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextfieldMontoMinActionPerformed

    private void BotonEditarFechaBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarFechaBloqueActionPerformed
        // TODO add your handling code here:
        //System.out.println("Fecha: "+TextfieldFechaBloqueo.getText());
        if(editandoFecha){
            BotonEditarFechaBloque.setIcon(new javax.swing.ImageIcon(getClass().getResource
        ("/pe/edu/pucp/centralizacionbancariasoft/img/edit30x30.png")));
            setFechaBloqueo(TextfieldFechaBloqueo.getText());
        }else{
            BotonEditarFechaBloque.setIcon(new javax.swing.ImageIcon(getClass().getResource
        ("/pe/edu/pucp/centralizacionbancariasoft/img/checked30x30.png")));
        }
        editandoFecha = !editandoFecha;
        TextfieldFechaBloqueo.setEnabled(editandoFecha);
        //setFechaBloqueo(TextfieldFechaBloqueo.getSelectedText());
    }//GEN-LAST:event_BotonEditarFechaBloqueActionPerformed

    private void BotonSicop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSicop1ActionPerformed
        // TODO add your handling code here:
        manager.seleccionarSicop();
        if(manager.getRutaSicop()!=""){
            TextfieldSicop.setText(manager.getRutaSicop());
            rutaSicopSeteada = true;
            cambiarColorDelBoton();
        } 
    }//GEN-LAST:event_BotonSicop1ActionPerformed

    private void BotonCenturiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCenturiaActionPerformed
        // TODO add your handling code here:
        manager.seleccionarCenturia();
        if(manager.getRutaCenturia() != ""){
            TextfieldCenturia.setText(manager.getRutaCenturia());
            rutaCenturiaSeteada = true;
            cambiarColorDelBoton();
        }
    }//GEN-LAST:event_BotonCenturiaActionPerformed

    private void BotenGenerarMacroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotenGenerarMacroActionPerformed
        // TODO add your handling code here:
        /*manager.setFechaBloqueo(this.fechaBloqueo);
        manager.setMontoMinimo(this.montoMinimo);
        manager.leerArchivos(rutaSicopSeteada, rutaCenturiaSeteada);
        manager.generarMacros();*/
        int flag = 0;
        if (!rutaSicopSeteada || !rutaCenturiaSeteada) {
            // Mostrar un JOptionPane para confirmar la acción
            int opcion = JOptionPane.showConfirmDialog(null, 
                "¿Seguro que solo quieres usar data del archivo " + 
                (rutaSicopSeteada ? "SICOP?" : "CENTURIA?"),
                "Advertencia",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

            // Verificar la opción seleccionada
            if (opcion == JOptionPane.YES_OPTION) {
                // Continuar con la acción
                manager.setFechaBloqueo(this.fechaBloqueo);
                manager.setMontoMinimo(this.montoMinimo);
                flag = manager.leerArchivos(rutaSicopSeteada, rutaCenturiaSeteada);
                if(flag > 0){
                    //PantallaDeCarga pantallaDeCarga = new PantallaDeCarga();
                    //pantallaDeCarga.setVisible(true);
                    manager.generarMacros();
                    //pantallaDeCarga.setVisible(false);
                }
                
            }
        } else {
            // Si ambas variables son verdaderas, ejecutar directamente
            manager.setFechaBloqueo(this.fechaBloqueo);
            manager.setMontoMinimo(this.montoMinimo);
            flag = manager.leerArchivos(rutaSicopSeteada, rutaCenturiaSeteada);
            if(flag > 0){
                manager.generarMacros();
            }
        }
        
    }//GEN-LAST:event_BotenGenerarMacroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotenGenerarMacro;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro BotonBorrarCenturia;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro BotonBorrarSicop;
    private javax.swing.JButton BotonCenturia;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro BotonEditarFechaBloque;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro BotonEditarMontoMin;
    private javax.swing.JButton BotonSicop1;
    private javax.swing.JLabel LabelCenturia;
    private javax.swing.JLabel LabelFechaBloqueo;
    private javax.swing.JLabel LabelInstr;
    private javax.swing.JLabel LabelMontoMin;
    private javax.swing.JLabel LabelSicop;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelCarga;
    private javax.swing.JPanel PanelCenturia;
    private javax.swing.JPanel PanelConfig;
    private javax.swing.JPanel PanelInstr;
    private javax.swing.JPanel PanelSicop;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JTextField TextfieldCenturia;
    private javax.swing.JTextField TextfieldFechaBloqueo;
    private javax.swing.JTextField TextfieldMontoMin;
    private javax.swing.JTextField TextfieldSicop;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro rSButtonMetro2;
    // End of variables declaration//GEN-END:variables
}
