/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.pucp.centralizacionbancariasoft.forms;
//import org.netbeans.lib.awtextra.AbsoluteConstraints;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author jyalico
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        //\main\resources\pe\edu\pucp\centralizacionbancariasoft\img
        setIconImage(new ImageIcon(getClass().getResource("/pe/edu/pucp/centrali"
                + "zacionbancariasoft/img/logoPUCP95.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrograma = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        OpcionMacros = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        OpcionOtros2 = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        OpcionOtros1 = new pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro();
        PanelContenedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrograma.setBackground(new java.awt.Color(155, 186, 235));

        PanelTitulo.setBackground(new java.awt.Color(4, 35, 84));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/pucp/centralizacionbancariasoft/img/logoPUCP95.png"))); // NOI18N
        jLabel1.setText("CENTRALIZACIÓN BANCARIA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jLabel1.setIconTextGap(20);

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelBotones.setBackground(new java.awt.Color(4, 35, 84));

        OpcionMacros.setBackground(new java.awt.Color(4, 35, 84));
        OpcionMacros.setText("Macros BCP y BBVA");
        OpcionMacros.setColorNormal(new java.awt.Color(4, 35, 84));
        OpcionMacros.setColorPressed(new java.awt.Color(155, 186, 235));
        OpcionMacros.setColorTextPressed(new java.awt.Color(0, 0, 0));
        OpcionMacros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionMacrosActionPerformed(evt);
            }
        });

        OpcionOtros2.setBackground(new java.awt.Color(4, 35, 84));
        OpcionOtros2.setText("OTRO");
        OpcionOtros2.setColorNormal(new java.awt.Color(4, 35, 84));
        OpcionOtros2.setColorPressed(new java.awt.Color(155, 186, 235));
        OpcionOtros2.setColorTextPressed(new java.awt.Color(0, 0, 0));
        OpcionOtros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionOtros2ActionPerformed(evt);
            }
        });

        OpcionOtros1.setBackground(new java.awt.Color(4, 35, 84));
        OpcionOtros1.setText("OTRO");
        OpcionOtros1.setColorNormal(new java.awt.Color(4, 35, 84));
        OpcionOtros1.setColorPressed(new java.awt.Color(155, 186, 235));
        OpcionOtros1.setColorTextPressed(new java.awt.Color(0, 0, 0));
        OpcionOtros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionOtros1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpcionMacros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OpcionOtros2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
            .addComponent(OpcionOtros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addComponent(OpcionMacros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(OpcionOtros1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(OpcionOtros2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 253, Short.MAX_VALUE))
        );

        PanelContenedor.setBackground(new java.awt.Color(155, 186, 235));
        PanelContenedor.setPreferredSize(new java.awt.Dimension(750, 400));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO");

        javax.swing.GroupLayout PanelContenedorLayout = new javax.swing.GroupLayout(PanelContenedor);
        PanelContenedor.setLayout(PanelContenedorLayout);
        PanelContenedorLayout.setHorizontalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelContenedorLayout.setVerticalGroup(
            PanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelProgramaLayout = new javax.swing.GroupLayout(PanelPrograma);
        PanelPrograma.setLayout(PanelProgramaLayout);
        PanelProgramaLayout.setHorizontalGroup(
            PanelProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelProgramaLayout.createSequentialGroup()
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelProgramaLayout.setVerticalGroup(
            PanelProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProgramaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionMacrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionMacrosActionPerformed
        // TODO add your handling code here:
        // Crear una instancia del formulario FrmMacroBancos
        System.out.println("opcion 1 press");
        FrmMacroBancos frmMacroBancos = new FrmMacroBancos();
        frmMacroBancos.setSize(PanelContenedor.getWidth(), PanelContenedor.getHeight());
        frmMacroBancos.setLocation(0,0);
        // Mostrar el formulario FrmMacroBancos en el PanelContenedor
        PanelContenedor.removeAll();
        PanelContenedor.add(frmMacroBancos, BorderLayout.CENTER);
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }//GEN-LAST:event_OpcionMacrosActionPerformed

    private void OpcionOtros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionOtros2ActionPerformed
        // TODO add your handling code here:
        System.out.println("opcion 2 press");
        PanelContenedor.removeAll();
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }//GEN-LAST:event_OpcionOtros2ActionPerformed

    private void OpcionOtros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionOtros1ActionPerformed
        // TODO add your handling code here:
        System.out.println("opcion 3 press");
        PanelContenedor.removeAll();
        PanelContenedor.revalidate();
        PanelContenedor.repaint();
    }//GEN-LAST:event_OpcionOtros1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro OpcionMacros;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro OpcionOtros1;
    private pe.edu.pucp.centralizacionbancariasoft.graficos.RSButtonMetro OpcionOtros2;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelPrograma;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
